// <auto-generated />
namespace Mooc.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _01032021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01032021));
        
        string IMigrationMetadata.Id
        {
            get { return "202101030318355_01032021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
